# permissions for end users to edit redisshakes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redisshake-editor-role
rules:
- apiGroups:
  - middle.alauda.cn
  resources:
  - redisshakes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - middle.alauda.cn
  resources:
  - redisshakes/status
  verbs:
  - get
