# permissions for end users to view redisproxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redisproxy-viewer-role
rules:
- apiGroups:
  - middle.alauda.cn
  resources:
  - redisproxies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - middle.alauda.cn
  resources:
  - redisproxies/status
  verbs:
  - get
