# permissions for end users to edit redisproxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redisproxy-editor-role
rules:
- apiGroups:
  - middle.alauda.cn
  resources:
  - redisproxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - middle.alauda.cn
  resources:
  - redisproxies/status
  verbs:
  - get
