# permissions for end users to view redisshakes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redisshake-viewer-role
rules:
- apiGroups:
  - middle.alauda.cn
  resources:
  - redisshakes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - middle.alauda.cn
  resources:
  - redisshakes/status
  verbs:
  - get
