
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - deployments
  - endpoints
  - events
  - namespaces
  - persistentvolumeclaims
  - pods
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - middle.alauda.cn
  resources:
  - redisbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - middle.alauda.cn
  resources:
  - redisbackups/finalizers
  verbs:
  - update
- apiGroups:
  - middle.alauda.cn
  resources:
  - redisbackups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - middle.alauda.cn
  resources:
  - redisfailovers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - middle.alauda.cn
  resources:
  - redisfailovers/finalizers
  verbs:
  - update
- apiGroups:
  - middle.alauda.cn
  resources:
  - redisfailovers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
